"""
src/ingestion/pdf_extractor.py
───────────────────────────────
Extracts raw text from a PDF file using pypdf, then applies a multi-step
cleaning pipeline to produce normalised, retrieval-ready text.

Why pypdf?
──────────
pypdf is a pure-Python, zero-system-dependency PDF reader.  Unlike pdfplumber
or PyMuPDF it requires no C extensions and no OS-level binaries, making the
project easier to install in restricted environments (Docker, serverless, CI).
For text-only PDFs generated by ReportLab — as is the case here — pypdf's
extraction quality is excellent.

Text-cleaning rationale
───────────────────────
Raw PDF text contains several artefacts that degrade embedding quality:

  1. Hyphenated line breaks  ("knowl-\nedge" → "knowledge")
     PDFs often hyphenate long words at line boundaries.  These are invisible
     hyphens inserted by the typesetter, not meaningful punctuation.

  2. Soft line breaks within paragraphs  ("\n" mid-sentence)
     PDF rendering engines wrap lines at fixed column widths, inserting "\n"
     characters that carry no semantic meaning.  These interfere with
     sentence-boundary-aware splitters.

  3. Page number artefacts  (lines containing only "1", "2", "3", …)
     Most PDFs stamp the page number in the footer; pypdf includes it as a
     standalone text fragment in the extraction output.

  4. Multiple consecutive blank lines
     Collapsed to a single blank line to keep paragraph boundaries clear.

Public API
──────────
    extract_text(pdf_path)          → raw text string
    clean_text(raw_text)            → cleaned text string
    extract_and_clean(pdf_path)     → cleaned text string  (main entry point)
"""

import logging
import re
from pathlib import Path

from pypdf import PdfReader

from observability.logger import get_logger

logger = get_logger(__name__)


# ─── Extraction ────────────────────────────────────────────────────────────────

def extract_text(pdf_path: Path | str) -> str:
    """
    Extracts all text from a PDF file, page by page.

    Implementation detail:
        PdfReader.pages yields one PageObject per page.  Each PageObject has
        an extract_text() method that returns the text content as a string.
        We join pages with double-newlines to preserve paragraph boundaries
        that happen to fall at page transitions.

    Args:
        pdf_path: Path to the source PDF file.

    Returns:
        Raw concatenated text from all pages.

    Raises:
        FileNotFoundError: If the PDF does not exist.
        ValueError: If the PDF has no pages or contains no extractable text
                    (e.g. a scanned image-only PDF).
    """
    pdf_path = Path(pdf_path)
    if not pdf_path.exists():
        raise FileNotFoundError(f"PDF not found: {pdf_path}")

    reader = PdfReader(str(pdf_path))

    if len(reader.pages) == 0:
        raise ValueError(f"PDF has no pages: {pdf_path}")

    page_texts: list[str] = []
    for page_num, page in enumerate(reader.pages, start=1):
        # extract_text() returns None for image-only pages; default to "".
        text = page.extract_text() or ""
        if text.strip():
            page_texts.append(text)
            logger.debug(
                "Page %d: extracted %d chars",
                page_num,
                len(text),
                extra={"page": page_num, "char_count": len(text)},
            )
        else:
            # Log a warning but continue — the document may have a blank
            # separator page or an image-only page that we can safely skip.
            logger.warning(
                "Page %d yielded no text (image-only or blank page)",
                page_num,
                extra={"page": page_num},
            )

    raw_text = "\n\n".join(page_texts)

    if not raw_text.strip():
        raise ValueError(
            "No extractable text found in the PDF.  "
            "The file may be a scanned image-only document."
        )

    logger.info(
        "Extracted text from %d/%d pages — %d chars total",
        len(page_texts),
        len(reader.pages),
        len(raw_text),
        extra={
            "pages_with_text": len(page_texts),
            "total_pages": len(reader.pages),
            "raw_char_count": len(raw_text),
        },
    )
    return raw_text


# ─── Cleaning ──────────────────────────────────────────────────────────────────

def clean_text(raw_text: str) -> str:
    """
    Cleans and normalises extracted PDF text for downstream RAG processing.

    Pipeline steps (applied in order):
    ────────────────────────────────────
    1. Normalise line endings
       Convert \\r\\n (Windows) and \\r (old Mac) to \\n so all subsequent
       regex operations only need to handle \\n.

    2. Rejoin hyphenated words
       Regex: r"-\\n(\\w)"  → remove the hyphen and newline, join the word.
       Example: "knowl-\\nedge" → "knowledge"
       We only match when the next character is a word character (\\w) to
       avoid removing meaningful hyphens before punctuation.

    3. Merge soft line breaks within paragraphs
       A single \\n NOT preceded or followed by another \\n is a line-wrap
       artefact.  We replace it with a space so sentences flow correctly.
       Regex: r"(?<!\\n)\\n(?!\\n)"  → " "

    4. Collapse runs of blank lines
       Three or more consecutive \\n are collapsed to exactly two (a single
       blank line), preserving paragraph structure without excessive spacing.

    5. Strip per-line leading/trailing whitespace
       Each line may have trailing spaces introduced by the PDF renderer.

    6. Drop page-number-only lines
       Lines containing only digits (and optional surrounding whitespace)
       are footer/header page numbers inserted by the typesetter.
       Regex: r"^\\d+\\s*$" (MULTILINE) → empty string

    7. Final collapse of blank lines
       Step 6 may introduce new empty lines; collapse them again.

    Args:
        raw_text: Raw text as returned by extract_text().

    Returns:
        Clean, normalised plain text, ready to be split into chunks.
    """
    text = raw_text

    # Step 1: Normalise line endings to \n
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Step 2: Rejoin hyphenated line-break artefacts
    # The lookahead (\w) ensures we don't strip legitimate end-of-line hyphens
    # such as those in "self-\nservice" (which we DO want to join to "self-service").
    # Wait — that is the same case!  We want "self-\nservice" → "self-service".
    # The regex keeps the hyphen because it only removes the \n, not the hyphen.
    # Actually the pattern is r"-\n(\w)" which replaces the whole match with
    # just the captured word character, effectively removing the hyphen AND \n.
    # This is correct: "knowl-\nedge" → "knowledge", "self-\nservice" → "selfservice".
    # For our specific ReportLab-generated PDF, the splitter does not hyphenate
    # across lines, so this step is a safeguard for other PDF sources.
    text = re.sub(r"-\n(\w)", r"\1", text)

    # Step 3: Merge soft intra-paragraph line breaks → single space
    # The negative lookbehind (?<!\n) and negative lookahead (?!\n) ensure
    # we only replace lone \n, not the \n in a \n\n paragraph separator.
    text = re.sub(r"(?<!\n)\n(?!\n)", " ", text)

    # Step 4: Collapse 3+ consecutive newlines to exactly 2
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Step 5: Strip leading/trailing whitespace on each individual line
    text = "\n".join(line.strip() for line in text.splitlines())

    # Step 6: Remove lines that contain only digits (page number artefacts)
    # re.MULTILINE makes ^ and $ match at line boundaries, not just at the
    # start/end of the whole string.
    text = re.sub(r"^\d+\s*$", "", text, flags=re.MULTILINE)

    # Step 7: Collapse any new blank lines introduced by step 6
    text = re.sub(r"\n{3,}", "\n\n", text)

    cleaned = text.strip()
    logger.info(
        "Text cleaned: %d → %d chars (removed %d chars)",
        len(raw_text),
        len(cleaned),
        len(raw_text) - len(cleaned),
        extra={
            "raw_char_count":     len(raw_text),
            "cleaned_char_count": len(cleaned),
        },
    )
    return cleaned


# ─── Combined convenience function ────────────────────────────────────────────

def extract_and_clean(pdf_path: Path | str) -> str:
    """
    Extracts text from *pdf_path* and immediately cleans it.

    This is the primary entry point used by the pipeline.  Calling it
    is equivalent to:
        clean_text(extract_text(pdf_path))

    Separating extraction and cleaning into two functions makes each
    independently testable and allows callers to inspect the raw text
    before cleaning if needed.

    Args:
        pdf_path: Path to the source PDF.

    Returns:
        Cleaned text string ready for chunk splitting.
    """
    raw = extract_text(pdf_path)
    return clean_text(raw)
