"""
src/output_formatter.py
───────────────────────
Converts a list of QuestionDict objects into a well-structured, PDF-ready
Markdown document and writes it to disk.

Markdown structure
──────────────────
  # Practice Questions: <Title>
  *Generated on: <date>*
  *Source document: <filename>*

  ---

  ## Question 1
  **<question text>**

  - **A)** <choice A>
  - **B)** <choice B>
  - **C)** <choice C>
  - **D)** <choice D>

  > **Correct Answer:** C

  <details>
  <summary>📖 Explanation</summary>

  <explanation text>

  </details>

  ---

  ## Question 2
  ...

  ---
  *End of Practice Questions*

Public API
──────────
    format_questions_to_markdown(questions, source_name, output_path)
                                            → str  (full markdown text)
"""

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

QuestionDict = dict[str, Any]

# Choice label → display label mapping
CHOICE_LABELS = {"A": "A", "B": "B", "C": "C", "D": "D"}


def _render_question(q: QuestionDict, number: int) -> str:
    """
    Renders a single question dict as a Markdown section.

    Args:
        q:      Validated QuestionDict.
        number: Display number (1-based).

    Returns:
        Markdown string for this question.
    """
    lines: list[str] = []

    lines.append(f"## Question {number}\n")
    lines.append(f"**{q.get('question', '[No question text]')}**\n")

    choices: dict[str, str] = q.get("choices", {})
    for label in ("A", "B", "C", "D"):
        text = choices.get(label, "—")
        lines.append(f"- **{label})** {text}")

    lines.append("")
    correct = q.get("correct_answer", "?")
    lines.append(f"> ✅ **Correct Answer: {correct}**")
    lines.append("")

    explanation = q.get("explanation", "No explanation provided.")
    lines.append("**Explanation:**")
    lines.append("")
    lines.append(explanation)

    lines.append("")
    lines.append("---")
    lines.append("")

    return "\n".join(lines)


def format_questions_to_markdown(
    questions: list[QuestionDict],
    source_name: str = "sample_document.pdf",
    output_path: Path | str | None = None,
) -> str:
    """
    Formats a list of questions as a Markdown document and optionally saves it.

    Args:
        questions:   List of validated QuestionDict objects.
        source_name: Filename or label of the source document (shown in header).
        output_path: If provided, writes the Markdown to this file path.

    Returns:
        The complete Markdown string.

    Raises:
        ValueError: If *questions* is empty.
        OSError:    If writing to *output_path* fails.
    """
    if not questions:
        raise ValueError("Cannot format an empty question list.")

    now = datetime.now(tz=timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    total = len(questions)

    # ── Document header ────────────────────────────────────────────────────────
    header_lines = [
        "# Practice Questions",
        "",
        f"*Source document:* `{source_name}`",
        f"*Generated on:* {now}",
        f"*Total questions:* {total}",
        "",
        "> **Note:** All questions are original and generated exclusively from the "
        "source document above. They are intended for study and educational purposes only.",
        "",
        "---",
        "",
    ]

    # ── Questions ──────────────────────────────────────────────────────────────
    question_sections: list[str] = [
        _render_question(q, i + 1) for i, q in enumerate(questions)
    ]

    # ── Footer ─────────────────────────────────────────────────────────────────
    footer_lines = [
        "",
        "---",
        "",
        f"*End of Practice Questions — {total} questions generated by AI Q&A Agent.*",
    ]

    full_markdown = (
        "\n".join(header_lines)
        + "\n".join(question_sections)
        + "\n".join(footer_lines)
    )

    # ── Save to disk ───────────────────────────────────────────────────────────
    if output_path is not None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(full_markdown, encoding="utf-8")
        logger.info("Markdown saved to: %s", output_path.resolve())

    return full_markdown


# ── Backward-compat re-export ─────────────────────────────────────────────────
# Canonical implementation moved to src/output/output_formatter.py.
from src.output.output_formatter import format_questions_to_markdown  # noqa: F811, E402
